# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 375)
        Form.setStyleSheet("background: rgb(85, 85, 255)\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 30, 271, 71))
        self.label.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(50, 190, 151, 17))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255)")
        self.checkBox.setObjectName("checkBox")
        self.cb_alphabete = QtWidgets.QCheckBox(Form)
        self.cb_alphabete.setGeometry(QtCore.QRect(50, 230, 161, 17))
        self.cb_alphabete.setStyleSheet("color: rgb(255, 255, 255)")
        self.cb_alphabete.setObjectName("cb_alphabete")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(50, 130, 171, 21))
        self.result.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.result.setObjectName("result")
        self.btn_generate = QtWidgets.QPushButton(Form)
        self.btn_generate.setGeometry(QtCore.QRect(150, 280, 111, 51))
        self.btn_generate.setStyleSheet("background: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.btn_generate.setObjectName("btn_generate")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Генератор паролів"))
        self.checkBox.setText(_translate("Form", "Використовувати числа"))
        self.cb_alphabete.setText(_translate("Form", "Використовувати алфавіт"))
        self.result.setText(_translate("Form", "Тут буде пароль"))
        self.btn_generate.setText(_translate("Form", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
